'use client'

import { createContext, useContext, useEffect, useState } from 'react'

type Lang = 'vi' | 'en'

interface LanguageContextType {
  lang: Lang
  setLang: (lang: Lang) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'vi',
  setLang: () => {},
  t: (key) => key,
})

export const useLanguage = () => useContext(LanguageContext)

const translations: Record<Lang, Record<string, string>> = {
  vi: {
    // TopBar
    'topbar.notifications': 'Thông báo',
    'topbar.vendor_badge': 'Nhà bán hàng',
    'topbar.new_order': 'Đơn hàng mới!',
    'topbar.order_pending': 'đang chờ xử lý.',
    'topbar.no_notifications': 'Không có thông báo mới nào',
    'topbar.view_all': 'Xem tất cả',
    'topbar.wallet': 'Ví tiền',
    'topbar.profile': 'Hồ sơ',
    'topbar.settings': 'Cài đặt',
    'topbar.logout': 'Đăng xuất',
    'topbar.balance': 'Số dư khả dụng',
    'topbar.points': 'Điểm thưởng',
    'topbar.topup': 'Nạp tiền ngay',
    'topbar.topup_short': 'Nạp thêm',
    'topbar.mark_all_read': 'Đánh dấu tất cả đã đọc',

    // Side nav
    'nav.overview': 'Tổng quan',
    'nav.stores': 'Cửa hàng',
    'nav.menu': 'Thực đơn',
    'nav.orders': 'Đơn hàng',
    'nav.manage_orders': 'Quản lý đơn hàng',
    'nav.manage_store': 'Quản lý cửa hàng',
    'nav.manage_menu': 'Quản lý thực đơn',
    'nav.manage_staff': 'Quản lý nhân viên',
    'nav.manage_users': 'Quản lý người dùng',
    'nav.approve_stores': 'Duyệt cửa hàng',
    'nav.wallet': 'Ví tiền',

    // Landing page
    'landing.tagline': 'Nhanh – Ngon – Tiện lợi',
    'landing.description': 'Đặt món từ căn tin Bách Khoa ngay trên trình duyệt. Tiết kiệm thời gian, tận hưởng bữa ăn ngon miệng trước và sau giờ học căng thẳng.',
    'landing.order_now': 'Gọi món ngay',
    'landing.feature_preorder': 'Đặt trước',
    'landing.feature_preorder_desc': 'Chọn món trước giờ nghỉ, không cần xếp hàng.',
    'landing.feature_food': 'Món ngon',
    'landing.feature_food_desc': 'Thực đơn đa dạng phong phú, giá phải chăng.',
    'landing.feature_time': 'Đúng giờ',
    'landing.feature_time_desc': 'Biết được khi nào món ăn sẵn sàng để lấy.',
    'landing.feature_easy': 'Dễ dùng',
    'landing.feature_easy_desc': 'Giao diện thân thiện, dùng là thích ngay.',
    'landing.cta_title': 'Sẵn sàng đặt món chưa?',
    'landing.cta_desc': 'Mỗi bữa ăn là một niềm vui nhỏ trong ngày học tập của bạn.',
    'landing.cta_btn': 'Bắt đầu ngay',

    // Login
    'login.title': 'Đăng nhập',
    'login.welcome': 'Chào mừng trở lại',
    'login.email_invalid': 'Email không hợp lệ',
    'login.password_required': 'Vui lòng nhập mật khẩu',
    'login.email': 'Email',
    'login.password': 'Mật khẩu',
    'login.forgot': 'Quên mật khẩu?',
    'login.submit': 'Đăng nhập',
    'login.no_account': 'Chưa có tài khoản?',
    'login.register': 'Đăng ký ngay',
    'login.success': 'Đăng nhập thành công',
    'login.failed': 'Đăng nhập thất bại',

    // Register
    'register.title': 'Đăng ký tài khoản',
    'register.subtitle': 'Trở thành thành viên',
    'register.fullname': 'Họ và tên',
    'register.fullname_placeholder': 'Nguyễn Văn A',
    'register.fullname_error': 'Họ và tên phải có ít nhất 2 ký tự',
    'register.email': 'Email',
    'register.email_placeholder': 'email@example.com',
    'register.email_invalid': 'Email không hợp lệ',
    'register.student_id': 'Mã số sinh viên',
    'register.student_id_placeholder': 'XXXXXXX',
    'register.student_id_error': 'Mã số sinh viên phải có đúng 7 ký tự',
    'register.gender': 'Giới tính',
    'register.gender_select': 'Chọn giới tính',
    'register.gender_male': 'Nam',
    'register.gender_female': 'Nữ',
    'register.dob': 'Ngày sinh',
    'register.day': 'Ngày',
    'register.month': 'Tháng',
    'register.year': 'Năm',
    'register.phone': 'Số điện thoại',
    'register.phone_placeholder': '0xxxxxxxxx',
    'register.phone_min': 'SĐT tối thiểu 10 số',
    'register.phone_digits': 'SĐT chỉ được chứa số',
    'register.password': 'Mật khẩu',
    'register.password_min': 'Mật khẩu phải có ít nhất 6 ký tự',
    'register.confirm_password': 'Nhập lại mật khẩu',
    'register.confirm_mismatch': 'Mật khẩu nhập lại không khớp',
    'register.submit': 'Đăng ký',
    'register.have_account': 'Đã có tài khoản?',
    'register.login': 'Đăng nhập',
    'register.dob_invalid': 'Ngày sinh không hợp lệ',
    'register.success': 'Đăng ký thành công! Vui lòng kiểm tra email để xác thực tài khoản.',
    'register.failed': 'Đăng ký thất bại',
    'register.gender_error': 'Vui lòng chọn giới tính',
    'register.day_error': 'Vui lòng chọn ngày',
    'register.month_error': 'Vui lòng chọn tháng',
    'register.year_error': 'Vui lòng chọn năm',

    // Verify email
    'verify.title': 'Xác thực tài khoản',
    'verify.welcome': 'Chào mừng bạn đến với',
    'verify.check_inbox': 'Kiểm tra hộp thư của bạn',
    'verify.description': 'Chúng tôi đã gửi một liên kết xác thực đến địa chỉ email của bạn. Vui lòng kiểm tra hộp thư (bao gồm cả mục Spam) và làm theo hướng dẫn để kích hoạt tài khoản.',
    'verify.continue': 'Tiếp tục đăng nhập',
    'verify.back_home': 'Quay lại trang chủ',

    // Account activation
    'activation.activating': 'Đang kích hoạt tài khoản...',
    'activation.done': 'Hoàn tất!',
    'activation.success_desc': 'Tài khoản của bạn đã được kích hoạt và sẵn sàng sử dụng.',
    'activation.failed': 'Kích hoạt thất bại',
    'activation.failed_desc': 'Mã xác thực không hợp lệ hoặc đã hết hạn.',
    'activation.login': 'Đăng nhập ngay',
    'activation.retry': 'Thử đăng ký lại',
    'activation.back_login': 'Quay lại đăng nhập',
    'activation.toast_success': 'Kích hoạt tài khoản thành công!',
    'activation.toast_failed': 'Kích hoạt thất bại. Liên kết có thể đã hết hạn hoặc không hợp lệ.',

    // Forgot password
    'forgot.title': 'Khôi phục mật khẩu',
    'forgot.step1': 'Nhập email để tìm lại tài khoản của bạn',
    'forgot.step2': 'Xác thực danh tính của bạn',
    'forgot.step3': 'Tạo mật khẩu mới an toàn hơn',
    'forgot.step4': 'Tài khoản đã sẵn sàng',
    'forgot.email_label': 'Email đăng ký',
    'forgot.send_otp': 'Gửi mã OTP',
    'forgot.back_login': 'Quay lại đăng nhập',
    'forgot.otp_sent_to': 'Nhập mã 6 số chúng tôi vừa gửi tới',
    'forgot.verify': 'Xác thực',
    'forgot.resend_after': 'Gửi lại sau {s}s',
    'forgot.no_code': 'Không nhận được mã?',
    'forgot.resend': 'Gửi lại',
    'forgot.other_email': 'Chọn email khác',
    'forgot.new_password': 'Mật khẩu mới',
    'forgot.confirm_password': 'Nhập lại mật khẩu',
    'forgot.password_mismatch': 'Mật khẩu nhập lại không khớp',
    'forgot.change_password': 'Đổi mật khẩu',
    'forgot.success_title': 'Thành công!',
    'forgot.success_desc': 'Mật khẩu của bạn đã được cập nhật.',
    'forgot.login': 'Đăng nhập ngay',
    'forgot.otp_sent': 'Mã OTP đã được gửi đến email của bạn',
    'forgot.otp_verified': 'Xác thực OTP thành công!',
    'forgot.otp_wrong': 'Mã OTP không đúng',
    'forgot.changed': 'Đổi mật khẩu thành công',

    // Dashboard
    'dashboard.greeting_morning': 'Chào buổi sáng',
    'dashboard.greeting_afternoon': 'Chào buổi chiều',
    'dashboard.greeting_evening': 'Chào buổi tối',
    'dashboard.question': 'Bạn muốn ăn gì hôm nay?',
    'dashboard.explore_stores': 'Khám phá cửa hàng',
    'dashboard.view_menu': 'Xem thực đơn',

    // Vendors page
    'vendors.title': 'Tất cả cửa hàng',
    'vendors.subtitle': 'Chọn cửa hàng yêu thích của bạn và đặt món ngay.',
    'vendors.search': 'Tìm kiếm cửa hàng...',
    'vendors.not_found': 'Không tìm thấy cửa hàng nào.',

    // Menu page
    'menu.title': 'Thực đơn',
    'menu.subtitle': 'Khám phá các món ăn ngon từ các quán trong BKafeteria.',
    'menu.not_found': 'Không tìm thấy món ăn nào trong danh mục này.',
    'menu.fresh_daily': 'Được chế biến tươi ngon mỗi ngày.',
    'menu.remaining': 'Còn {n} phần!',
    'menu.added_to_cart': 'Đã thêm {name} vào giỏ hàng',
    'menu.added_n_items': 'Đã thêm {n} x {name} vào giỏ hàng',
    'menu.desc_title': 'Mô tả món ăn',
    'menu.desc_default': 'Món ăn được chế biến từ những nguyên liệu tươi ngon nhất, đảm bảo vệ sinh an toàn thực phẩm và hương vị đậm đà khó quên.',
    'menu.price_per_unit': 'Giá mỗi phần',
    'menu.add_to_cart_btn': 'Thêm vào giỏ',
    'menu.cat_all': 'Tất cả',
    'menu.cat_pastries': 'Bánh ngọt',
    'menu.cat_meals': 'Bữa chính',
    'menu.cat_beverages': 'Đồ uống',
    'menu.cat_snacks': 'Ăn vặt',
    'menu.cat_desserts': 'Tráng miệng',

    // Orders page
    'orders.title': 'Đơn hàng của tôi',
    'orders.subtitle': 'Theo dõi trạng thái đơn hàng của bạn theo thời gian thực.',
    'orders.refresh': 'Làm mới',
    'orders.empty': 'Chưa có đơn hàng nào',
    'orders.empty_desc': 'Khi bạn đặt món, chúng sẽ xuất hiện ở đây để bạn có thể theo dõi tiến độ.',
    'orders.order_now': 'Đặt món ngay',
    'orders.status_changed': 'Trạng thái đơn hàng: {status}',

    // Order card
    'order_card.id': 'Đơn hàng #',
    'order_card.total_amount': 'Tổng số tiền',
    'order_card.pay_btn': 'Thanh toán',
    'order_card.detail_btn': 'Chi tiết',
    'order_card.toast_pay_success': 'Thanh toán thành công!',
    'order_card.toast_pay_error': 'Thanh toán thất bại',

    // Order details
    'order_details.order_items': 'Món đã đặt',
    'order_details.unit_price': '{price}đ / món',
    'order_details.member_offer': 'Ưu đãi thành viên',
    'order_details.original_price': 'Giá gốc',
    'order_details.discount': 'Giảm giá',
    'order_details.subtotal': 'Thành tiền',
    'order_details.total_payment': 'Tổng thanh toán',
    'order_details.pickup_location': 'Địa điểm nhận món',
    'order_details.pickup_desc': 'Vui lòng đến quầy khi có thông báo "Hoàn thành"',
    'order_details.canceled_title': 'Đơn hàng đã bị hủy',
    'order_details.canceled_desc': 'Đơn hàng này đã được hủy và không còn được xử lý.',
    'order_details.ordered_at': 'Đặt lúc: {time}',
    'order_details.status_pending': 'Chờ thanh toán',
    'order_details.status_purchased': 'Đã thanh toán',
    'order_details.status_processing': 'Đang chế biến',
    'order_details.status_completed': 'Đã chuẩn bị',
    'order_details.status_delivered': 'Đã giao hàng',

    // Order statuses
    'order_status.pending': 'Chờ thanh toán',
    'order_status.purchased': 'Đã thanh toán',
    'order_status.processing': 'Đang chế biến',
    'order_status.completed': 'Hoàn thành',
    'order_status.delivered': 'Đã giao',
    'order_status.canceled': 'Đã hủy',

    // Vendor WebSocket
    'vendor_ws.new_order': 'Có đơn hàng mới!',
    'vendor_ws.new_order_desc': 'Đơn hàng #{id} vừa được đặt.',

    // Order detail
    'order_detail.title': 'Theo dõi đơn hàng',
    'order_detail.subtitle': 'Thông tin chi tiết và trạng thái đơn hàng của bạn.',
    'order_detail.not_found': 'Không tìm thấy đơn hàng',
    'order_detail.not_found_desc': 'Đơn hàng bạn đang tìm kiếm không tồn tại hoặc đã bị xóa.',
    'order_detail.back': 'Quay lại danh sách',

    // Wallet
    'wallet.title': 'Ví của tôi',
    'wallet.subtitle': 'Quản lý số dư và xem lịch sử giao dịch của bạn.',
    'wallet.recent_tx': 'Giao dịch gần đây',
    'wallet.no_tx': 'Chưa có giao dịch nào.',
    'wallet.balance': 'Số dư hiện tại',
    'wallet.deposit': 'Nạp tiền',
    'wallet.withdraw': 'Rút tiền',
    'wallet.toast_deposit': 'Tính năng nạp tiền sẽ sớm ra mắt qua VNPay/Momo!',
    'wallet.toast_withdraw': 'Tính năng rút tiền đang được phát triển',



    // Loading / Not found
    'loading.text': 'Đang tải dữ liệu...',
    'notfound.title': 'Không tìm thấy trang',
    'notfound.desc': 'Trang bạn tìm không tồn tại hoặc đã bị di chuyển.',
    'notfound.home': 'Về trang chủ',
    'notfound.back': 'Quay lại',

    // Admin - Users
    'admin.users.title': 'Quản lý người dùng',
    'admin.users.subtitle': 'Hệ thống quản lý tài khoản và phân quyền người dùng.',
    'admin.users.search': 'Tìm theo tên, email, SĐT...',
    'admin.users.all_roles': 'Tất cả vai trò',
    'admin.users.col_user': 'Người dùng',
    'admin.users.col_contact': 'Liên hệ',
    'admin.users.col_role': 'Vai trò',
    'admin.users.col_status': 'Trạng thái',
    'admin.users.col_action': 'Thao tác',
    'admin.users.active': 'Đang hoạt động',
    'admin.users.inactive': 'Đã khóa',
    'admin.users.change_role': 'Đổi vai trò',
    'admin.users.lock': 'Khóa tài khoản',
    'admin.users.activate': 'Kích hoạt',
    'admin.users.delete': 'Xóa tài khoản',
    'admin.users.page_info': 'Trang {page} / {total} ({count} người dùng)',
    'admin.users.role_dialog_title': 'Thay đổi vai trò',
    'admin.users.role_dialog_desc': 'Chọn vai trò mới cho người dùng {name}.',
    'admin.users.role_select': 'Chọn vai trò',
    'admin.users.role_warning': 'Cẩn trọng: Thay đổi vai trò có thể ảnh hưởng đến quyền truy cập của người dùng này vào hệ thống.',
    'admin.users.cancel': 'Hủy',
    'admin.users.confirm': 'Xác nhận',
    'admin.users.toast_role': 'Đã cập nhật vai trò cho {name}',
    'admin.users.toast_activated': 'Đã kích hoạt tài khoản {name}',
    'admin.users.toast_locked': 'Đã khóa tài khoản {name}',
    'admin.users.toast_deleted': 'Đã xóa tài khoản {name}',
    'admin.users.confirm_delete': 'Bạn có chắc chắn muốn xóa tài khoản {name}?',

    // Admin - Vendors
    'admin.vendors.title': 'Duyệt cửa hàng',
    'admin.vendors.subtitle': 'Quản lý và phê duyệt các cửa hàng đăng ký vào hệ thống.',
    'admin.vendors.search': 'Tìm theo tên cửa hàng...',
    'admin.vendors.filter': 'Bộ lọc',
    'admin.vendors.pending': 'Chờ duyệt',
    'admin.vendors.active': 'Đang hoạt động',
    'admin.vendors.rejected': 'Bị từ chối',
    'admin.vendors.closed': 'Đóng cửa',
    'admin.vendors.no_desc': 'Chưa có mô tả cho cửa hàng này.',
    'admin.vendors.no_cert': 'Chưa có chứng nhận',
    'admin.vendors.approve': 'Duyệt ngay',
    'admin.vendors.view': 'Xem chi tiết',
    'admin.vendors.empty': 'Không có yêu cầu nào',
    'admin.vendors.empty_desc': 'Hiện tại không có cửa hàng nào đang chờ phê duyệt hoặc khớp với tìm kiếm của bạn.',
    'admin.vendors.toast_approved': 'Đã phê duyệt cửa hàng {name}',

    // Manager - Vendor
    'manager.vendor.title': 'Cửa hàng của tôi',
    'manager.vendor.subtitle': 'Quản lý thông tin và trạng thái hoạt động của cửa hàng.',
    'manager.vendor.add_title': 'Đăng ký cửa hàng',
    'manager.vendor.edit_title': 'Cập nhật cửa hàng',
    'manager.vendor.card_title': 'Thông tin chi tiết',
    'manager.vendor.card_desc': 'Cập nhật các thông tin cơ bản về cửa hàng của bạn.',
    'manager.vendor.name': 'Tên cửa hàng',
    'manager.vendor.name_placeholder': 'VD: Cơm trưa Bách Khoa...',
    'manager.vendor.cert': 'Chứng nhận / Giấy phép',
    'manager.vendor.cert_placeholder': 'Giấy phép KD, ATTP...',
    'manager.vendor.desc': 'Mô tả cửa hàng',
    'manager.vendor.desc_placeholder': 'Mô tả về cửa hàng, món ăn đặc trưng...',
    'manager.vendor.open': 'Giờ mở cửa',
    'manager.vendor.close': 'Giờ đóng cửa',
    'manager.vendor.save': 'Lưu thông tin',
    'manager.vendor.submit': 'Gửi yêu cầu',
    'manager.vendor.stats': 'Thống kê nhanh',
    'manager.vendor.completed': 'Đơn hoàn thành',
    'manager.vendor.menu': 'Thực đơn',
    'manager.vendor.tip_title': 'Mẹo nhỏ',
    'manager.vendor.tip_desc': 'Cập nhật đầy đủ mô tả và hình ảnh chứng nhận giúp khách hàng tin tưởng và lựa chọn món ăn của bạn nhiều hơn.',
    'manager.vendor.no_vendor': 'Bạn chưa có cửa hàng',
    'manager.vendor.no_vendor_desc': 'Hãy đăng ký cửa hàng đầu tiên của bạn để bắt đầu kinh doanh trên BKafeteria.',
    'manager.vendor.dialog_desc': 'Xây dựng thương hiệu và quản lý vận hành cửa hàng của bạn một cách chuyên nghiệp.',
    'manager.vendor.dialog_hint': 'Cung cấp thông tin đầy đủ giúp cửa hàng dễ dàng được Admin phê duyệt hơn.',
    'manager.vendor.toast_register_success': 'Đã gửi yêu cầu đăng ký cửa hàng!',
    'manager.vendor.toast_success': 'Cập nhật thông tin cửa hàng thành công',
    'manager.vendor.toast_error': 'Cập nhật thất bại, vui lòng thử lại',
    'manager.vendor.status_pending': 'Chờ duyệt',
    'manager.vendor.status_accepted': 'Đang hoạt động',
    'manager.vendor.status_rejected': 'Bị từ chối',
    'manager.vendor.status_closed': 'Đóng cửa',

    // Manager - Menu
    'manager.menu.title': 'Quản lý thực đơn',
    'manager.menu.subtitle': 'Thêm, sửa, xóa và theo dõi số lượng món ăn trong thực đơn.',
    'manager.menu.add': 'Thêm món mới',
    'manager.menu.search': 'Tìm kiếm món ăn...',
    'manager.menu.empty': 'Không tìm thấy món ăn nào',
    'manager.menu.empty_desc': 'Thử thay đổi từ khóa tìm kiếm hoặc thêm món ăn mới vào thực đơn của bạn.',
    'manager.menu.edit_title': 'Cập nhật món ăn',
    'manager.menu.add_title': 'Thêm món ăn mới',
    'manager.menu.dialog_desc': 'Nhập thông tin món ăn để khách hàng có thể đặt ngay.',
    'manager.menu.dialog_add_hint': 'Tạo món mới cực nhanh',
    'manager.menu.dialog_update_hint': 'Cập nhật lại giao diện món',
    'manager.menu.form_image': 'Hình ảnh món ăn',
    'manager.menu.field_name': 'Tên món ăn',
    'manager.menu.field_name_placeholder': 'VD: Cơm sườn nướng...',
    'manager.menu.field_price': 'Giá bán (VNĐ)',
    'manager.menu.field_remaining': 'Số lượng còn lại',
    'manager.menu.field_category': 'Danh mục',
    'manager.menu.field_category_select': 'Chọn danh mục',
    'manager.menu.field_desc': 'Mô tả món ăn',
    'manager.menu.field_desc_placeholder': 'Thành phần, hương vị...',
    'manager.menu.cancel': 'Hủy',
    'manager.menu.save': 'Lưu thay đổi',
    'manager.menu.submit': 'Thêm món',
    'manager.menu.toast_updated': 'Cập nhật món ăn thành công',
    'manager.menu.toast_added': 'Thêm món ăn mới thành công',
    'manager.menu.confirm_delete': 'Bạn có chắc chắn muốn xóa món ăn này?',
    'manager.menu.no_desc': 'Không có mô tả cho món ăn này.',
    'manager.menu.no_image': 'Chưa có ảnh',
    'manager.menu.price': 'Giá bán',
    'manager.menu.remaining': 'Còn lại',

    // Manager - Orders
    'manager.orders.title': 'Quản lý đơn hàng',
    'manager.orders.subtitle': 'Theo dõi và xử lý các đơn hàng đang đến.',
    'manager.orders.processing': 'Đang xử lý',
    'manager.orders.history': 'Lịch sử đơn hàng',
    'manager.orders.vendor_order_id': 'ID Đơn hàng Vendor:',
    'manager.orders.finish': 'Hoàn thành',
    'manager.orders.empty_active': 'Không có đơn hàng nào đang chờ.',
    'manager.orders.empty_history': 'Chưa có lịch sử đơn hàng.',
    'manager.orders.toast_finished': 'Đã xác nhận hoàn thành đơn hàng!',
    'manager.orders.process': 'Xử lý',
    'manager.orders.sort': 'Sắp xếp',
    'manager.orders.newest': 'Mới nhất',
    'manager.orders.oldest': 'Cũ nhất',
    'manager.orders.toast_processing': 'Đơn hàng đang được xử lý',

    // Manager - Staff
    'manager.staff.title': 'Quản lý nhân viên',
    'manager.staff.subtitle': 'Quản lý đội ngũ nhân viên phục vụ tại cửa hàng của bạn.',
    'manager.staff.add': 'Thêm nhân viên',
    'manager.staff.search': 'Tìm nhân viên theo tên...',
    'manager.staff.remove': 'Gỡ nhân viên',
    'manager.staff.empty': 'Chưa có nhân viên nào',
    'manager.staff.empty_desc': 'Nhân viên sẽ giúp bạn xử lý đơn hàng nhanh chóng hơn. Hãy thêm nhân viên mới ngay!',
    'manager.staff.note_title': 'Lưu ý',
    'manager.staff.note_1': 'Chỉ những người dùng đã có tài khoản BKafeteria mới có thể được thêm làm nhân viên.',
    'manager.staff.note_2': 'Nhân viên có quyền xem và xử lý các đơn hàng thuộc cửa hàng của bạn.',
    'manager.staff.support_title': 'Hỗ trợ',
    'manager.staff.support_desc': 'Nếu gặp khó khăn trong việc quản lý nhân sự, hãy liên hệ với Quản trị viên hệ thống.',
    'manager.staff.dialog_title': 'Thêm nhân viên mới',
    'manager.staff.dialog_desc': 'Nhập email của người dùng để gán vai trò nhân viên cho cửa hàng của bạn.',
    'manager.staff.email_label': 'Email người dùng',
    'manager.staff.email_placeholder': 'example@student.hcmut.edu.vn',
    'manager.staff.cancel': 'Hủy',
    'manager.staff.submit': 'Thêm ngay',
    'manager.staff.toast_added': 'Đã thêm {email} vào danh sách nhân viên',
    'manager.staff.toast_error': 'Không tìm thấy người dùng hoặc có lỗi xảy ra',
    'manager.staff.confirm_remove': 'Bạn có chắc muốn gỡ {name} khỏi danh sách nhân viên?',
    'manager.staff.wip': 'Tính năng gỡ nhân viên đang được cập nhật',

    // Vendor card
    'vendor_card.status_pending': 'Đang chờ',
    'vendor_card.status_accepted': 'Đang mở',
    'vendor_card.status_rejected': 'Đã đóng',
    'vendor_card.status_closed': 'Tạm nghỉ',
    'vendor_card.no_desc': 'Chưa có mô tả cho cửa hàng này.',
    'vendor_card.view_menu': 'Xem thực đơn',

    // Menu page extra
    'menu.default_vendor': 'Cửa hàng',

    // Cart
    'cart.title': 'Giỏ hàng',
    'cart.clear': 'Xóa tất cả',
    'cart.empty_title': 'Giỏ hàng trống',
    'cart.empty_desc': 'Bạn chưa thêm món nào vào giỏ hàng cả.',
    'cart.start_shopping': 'Bắt đầu mua sắm',
    'cart.items_unit': 'món',
    'cart.total': 'Tổng cộng',
    'cart.checkout': 'Thanh toán ngay',

    // Profile page
    'profile.title': 'Hồ sơ cá nhân',
    'profile.subtitle': 'Quản lý thông tin tài khoản và cài đặt của bạn.',
    'profile.balance': 'Số dư',
    'profile.points': 'Điểm',
    'profile.status': 'Trạng thái',
    'profile.verified': 'Đã xác minh',
    'profile.personal_info': 'Thông tin cá nhân',
    'profile.personal_info_desc': 'Cập nhật các thông tin cơ bản về bạn để mọi người có thể nhận diện.',
    'profile.account_info': 'Thông tin tài khoản',
    'profile.account_info_desc': 'Các thông tin định danh không thể thay đổi.',
    'profile.fullname': 'Họ và tên',
    'profile.phone': 'Số điện thoại',
    'profile.gender': 'Giới tính',
    'profile.dob': 'Ngày sinh',
    'profile.email': 'Email',
    'profile.student_id': 'Mã số sinh viên',
    'profile.save': 'Lưu thay đổi',
    'profile.toast_success': 'Cập nhật hồ sơ thành công',
    'profile.toast_error': 'Cập nhật thất bại',

    'cart.toast_success': 'Đặt đơn hàng thành công!',
    'cart.toast_error': 'Có lỗi xảy ra khi đặt đơn hàng',
    'cart.providers.title': 'Giỏ hàng của bạn',
    'cart.providers.empty': 'Chưa có món ăn nào',
    'cart.providers.total': 'Tổng cộng:',
    'cart.providers.checkout': 'Thanh toán ngay',
    'cart.providers.added': 'Đã thêm {name} vào giỏ',
    'cart.providers.total_price': 'Tổng cộng:',

    // Roles
    'role.admin': 'Quản trị viên',
    'role.manager': 'Quản lý',
    'role.staff': 'Nhân viên',
    'role.customer': 'Khách hàng',

    // Common
    'common.cancel': 'Hủy',
    'common.search': 'Tìm kiếm...',
    'common.filter': 'Lọc',
    'common.switch_lang': 'Đổi ngôn ngữ',
    'common.vi': 'Tiếng Việt',
    'common.en': 'English',
    'common.change_to_vi': 'Đổi sang Tiếng Việt',
    'common.change_to_en': 'Đổi sang Tiếng Anh',

    // Categories
    'category.beverages': 'Đồ uống',
    'category.pastries': 'Bánh ngọt',
    'category.snacks': 'Ăn nhẹ',
    'category.meals': 'Bữa chính',
    'category.desserts': 'Tráng miệng',
    'common.edit': 'Sửa',
    'common.back': 'Quay lại',
    'common.next': 'Tiếp tục',
    'common.confirm': 'Xác nhận',
    'status.active': 'Hoạt động',
    'status.inactive': 'Ngừng hoạt động',
  },

  en: {
    // TopBar
    'topbar.notifications': 'Notifications',
    'topbar.vendor_badge': 'Vendor',
    'topbar.new_order': 'New Order!',
    'topbar.order_pending': 'is pending.',
    'topbar.no_notifications': 'No new notifications',
    'topbar.view_all': 'View all',
    'topbar.wallet': 'Wallet',
    'topbar.profile': 'Profile',
    'topbar.settings': 'Settings',
    'topbar.logout': 'Sign out',
    'topbar.balance': 'Available Balance',
    'topbar.points': 'Reward Points',
    'topbar.topup': 'Top up now',
    'topbar.topup_short': 'Top up',
    'topbar.mark_all_read': 'Mark all as read',

    // Side nav
    'nav.overview': 'Overview',
    'nav.stores': 'Vendors',
    'nav.menu': 'Menu',
    'nav.orders': 'Orders',
    'nav.manage_orders': 'Manage Orders',
    'nav.manage_store': 'My Vendor',
    'nav.manage_menu': 'Manage Menu',
    'nav.manage_staff': 'Manage Staff',
    'nav.manage_users': 'Manage Users',
    'nav.approve_stores': 'Approve Vendors',
    'nav.wallet': 'Wallet',

    // Landing page
    'landing.tagline': 'Fast – Delicious – Convenient',
    'landing.description': 'Order from BK cafeteria right in your browser. Save time and enjoy a great meal before and after class.',
    'landing.order_now': 'Order Now',
    'landing.feature_preorder': 'Pre-order',
    'landing.feature_preorder_desc': 'Pick your meal before break, no queuing.',
    'landing.feature_food': 'Good Food',
    'landing.feature_food_desc': 'Diverse menu at affordable prices.',
    'landing.feature_time': 'On Time',
    'landing.feature_time_desc': 'Know exactly when your food is ready.',
    'landing.feature_easy': 'Easy to Use',
    'landing.feature_easy_desc': 'Friendly interface you will love instantly.',
    'landing.cta_title': 'Ready to order?',
    'landing.cta_desc': 'Every meal is a small joy in your study day.',
    'landing.cta_btn': 'Get Started',

    // Login
    'login.title': 'Sign In',
    'login.welcome': 'Welcome back',
    'login.email_invalid': 'Invalid email',
    'login.password_required': 'Please enter your password',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.forgot': 'Forgot password?',
    'login.submit': 'Sign In',
    'login.no_account': "Don't have an account?",
    'login.register': 'Register now',
    'login.success': 'Signed in successfully',
    'login.failed': 'Sign in failed',

    // Register
    'register.title': 'Create Account',
    'register.subtitle': 'Become a member',
    'register.fullname': 'Full name',
    'register.fullname_placeholder': 'John Doe',
    'register.fullname_error': 'Full name must be at least 2 characters',
    'register.email': 'Email',
    'register.email_placeholder': 'email@example.com',
    'register.email_invalid': 'Invalid email',
    'register.student_id': 'Student ID',
    'register.student_id_placeholder': 'XXXXXXX',
    'register.student_id_error': 'Student ID must be exactly 7 characters',
    'register.gender': 'Gender',
    'register.gender_select': 'Select gender',
    'register.gender_male': 'Male',
    'register.gender_female': 'Female',
    'register.dob': 'Date of birth',
    'register.day': 'Day',
    'register.month': 'Month',
    'register.year': 'Year',
    'register.phone': 'Phone number',
    'register.phone_placeholder': '0xxxxxxxxx',
    'register.phone_min': 'Phone must be at least 10 digits',
    'register.phone_digits': 'Phone must contain digits only',
    'register.password': 'Password',
    'register.password_min': 'Password must be at least 6 characters',
    'register.confirm_password': 'Confirm password',
    'register.confirm_mismatch': 'Passwords do not match',
    'register.submit': 'Register',
    'register.have_account': 'Already have an account?',
    'register.login': 'Sign in',
    'register.dob_invalid': 'Invalid date of birth',
    'register.success': 'Registered! Please check your email to verify your account.',
    'register.failed': 'Registration failed',
    'register.gender_error': 'Please select your gender',
    'register.day_error': 'Please select day',
    'register.month_error': 'Please select month',
    'register.year_error': 'Please select year',

    // Verify email
    'verify.title': 'Verify Account',
    'verify.welcome': 'Welcome to',
    'verify.check_inbox': 'Check your inbox',
    'verify.description': 'We sent a verification link to your email address. Please check your inbox (including Spam) and follow the instructions to activate your account.',
    'verify.continue': 'Continue to sign in',
    'verify.back_home': 'Back to home',

    // Account activation
    'activation.activating': 'Activating your account...',
    'activation.done': 'Done!',
    'activation.success_desc': 'Your account has been activated and is ready to use.',
    'activation.failed': 'Activation failed',
    'activation.failed_desc': 'The verification code is invalid or has expired.',
    'activation.login': 'Sign in now',
    'activation.retry': 'Try registering again',
    'activation.back_login': 'Back to sign in',
    'activation.toast_success': 'Account activated successfully!',
    'activation.toast_failed': 'Activation failed. The link may have expired or is invalid.',

    // Forgot password
    'forgot.title': 'Reset Password',
    'forgot.step1': 'Enter your email to find your account',
    'forgot.step2': 'Verify your identity',
    'forgot.step3': 'Create a new secure password',
    'forgot.step4': 'Account is ready',
    'forgot.email_label': 'Registered email',
    'forgot.send_otp': 'Send OTP',
    'forgot.back_login': 'Back to sign in',
    'forgot.otp_sent_to': 'Enter the 6-digit code we just sent to',
    'forgot.verify': 'Verify',
    'forgot.resend_after': 'Resend in {s}s',
    'forgot.no_code': "Didn't receive a code?",
    'forgot.resend': 'Resend',
    'forgot.other_email': 'Use a different email',
    'forgot.new_password': 'New password',
    'forgot.confirm_password': 'Confirm password',
    'forgot.password_mismatch': 'Passwords do not match',
    'forgot.change_password': 'Change password',
    'forgot.success_title': 'Success!',
    'forgot.success_desc': 'Your password has been updated.',
    'forgot.login': 'Sign in now',
    'forgot.otp_sent': 'OTP sent to your email',
    'forgot.otp_verified': 'OTP verified successfully!',
    'forgot.otp_wrong': 'Incorrect OTP',
    'forgot.changed': 'Password changed successfully',

    // Dashboard
    'dashboard.greeting_morning': 'Good morning',
    'dashboard.greeting_afternoon': 'Good afternoon',
    'dashboard.greeting_evening': 'Good evening',
    'dashboard.question': 'What would you like to eat today?',
    'dashboard.explore_stores': 'Explore Vendors',
    'dashboard.view_menu': 'View Menu',

    // Vendors page
    'vendors.title': 'All Vendors',
    'vendors.subtitle': 'Pick your favourite vendor and order now.',
    'vendors.search': 'Search vendors...',
    'vendors.not_found': 'No vendors found.',

    // Menu page
    'menu.title': 'Menu',
    'menu.subtitle': 'Explore delicious dishes from vendors in BKafeteria.',
    'menu.not_found': 'No items found in this category.',
    'menu.fresh_daily': 'Made fresh every day.',
    'menu.remaining': '{n} left!',
    'menu.added_to_cart': 'Added {name} to cart',
    'menu.added_n_items': 'Added {n} x {name} to cart',
    'menu.desc_title': 'Description',
    'menu.desc_default': 'Made from the freshest ingredients, ensuring food safety and an unforgettable flavour.',
    'menu.price_per_unit': 'Price per unit',
    'menu.add_to_cart_btn': 'Add to cart',
    'menu.cat_all': 'All',
    'menu.cat_pastries': 'Pastries',
    'menu.cat_meals': 'Meals',
    'menu.cat_beverages': 'Beverages',
    'menu.cat_snacks': 'Snacks',
    'menu.cat_desserts': 'Desserts',

    // Orders page
    'orders.title': 'My Orders',
    'orders.subtitle': 'Track your order status in real time.',
    'orders.refresh': 'Refresh',
    'orders.empty': 'No orders yet',
    'orders.empty_desc': 'When you place orders they will appear here so you can track progress.',
    'orders.order_now': 'Order Now',
    'orders.status_changed': 'Order status: {status}',

    // Order card
    'order_card.id': 'Order #',
    'order_card.total_amount': 'Total Amount',
    'order_card.pay_btn': 'Pay Now',
    'order_card.detail_btn': 'Details',
    'order_card.toast_pay_success': 'Payment successful!',
    'order_card.toast_pay_error': 'Payment failed',

    // Order details
    'order_details.order_items': 'Ordered Items',
    'order_details.unit_price': '{price}đ / item',
    'order_details.member_offer': 'Member Offer',
    'order_details.original_price': 'Original Price',
    'order_details.discount': 'Discount',
    'order_details.subtotal': 'Subtotal',
    'order_details.total_payment': 'Total Payment',
    'order_details.pickup_location': 'Pickup Location',
    'order_details.pickup_desc': 'Please come to the counter when status is "Prepared"',
    'order_details.canceled_title': 'Order Canceled',
    'order_details.canceled_desc': 'This order has been canceled and is no longer being processed.',
    'order_details.ordered_at': 'Ordered at: {time}',
    'order_details.status_pending': 'Pending Payment',
    'order_details.status_purchased': 'Paid',
    'order_details.status_processing': 'Processing',
    'order_details.status_completed': 'Prepared',
    'order_details.status_delivered': 'Delivered',

    // Order statuses
    'order_status.pending': 'Pending payment',
    'order_status.purchased': 'Paid',
    'order_status.processing': 'Preparing',
    'order_status.completed': 'Completed',
    'order_status.delivered': 'Delivered',
    'order_status.canceled': 'Canceled',

    // Vendor WebSocket
    'vendor_ws.new_order': 'New order received!',
    'vendor_ws.new_order_desc': 'Order #{id} has been placed.',

    // Order detail
    'order_detail.title': 'Track Order',
    'order_detail.subtitle': 'Detailed information and status of your order.',
    'order_detail.not_found': 'Order not found',
    'order_detail.not_found_desc': 'The order you are looking for does not exist or has been deleted.',
    'order_detail.back': 'Back to list',

    // Wallet
    'wallet.title': 'My Wallet',
    'wallet.subtitle': 'Manage your balance and view transaction history.',
    'wallet.recent_tx': 'Recent Transactions',
    'wallet.no_tx': 'No transactions yet.',
    'wallet.balance': 'Current Balance',
    'wallet.deposit': 'Deposit',
    'wallet.withdraw': 'Withdraw',
    'wallet.toast_deposit': 'Deposit feature coming soon via VNPay/Momo!',
    'wallet.toast_withdraw': 'Withdrawal feature is under development',

    // Loading / Not found
    'loading.text': 'Loading...',
    'notfound.title': 'Page Not Found',
    'notfound.desc': 'The page you are looking for does not exist or has been moved.',
    'notfound.home': 'Go home',
    'notfound.back': 'Go back',

    // Admin - Users
    'admin.users.title': 'User Management',
    'admin.users.subtitle': 'Manage accounts and user roles.',
    'admin.users.search': 'Search by name, email, phone...',
    'admin.users.all_roles': 'All roles',
    'admin.users.col_user': 'User',
    'admin.users.col_contact': 'Contact',
    'admin.users.col_role': 'Role',
    'admin.users.col_status': 'Status',
    'admin.users.col_action': 'Actions',
    'admin.users.active': 'Active',
    'admin.users.inactive': 'Locked',
    'admin.users.change_role': 'Change role',
    'admin.users.lock': 'Lock account',
    'admin.users.activate': 'Activate',
    'admin.users.delete': 'Delete account',
    'admin.users.page_info': 'Page {page} / {total} ({count} users)',
    'admin.users.role_dialog_title': 'Change Role',
    'admin.users.role_dialog_desc': 'Select a new role for {name}.',
    'admin.users.role_select': 'Select role',
    'admin.users.role_warning': 'Warning: Changing the role may affect this user\'s access to the system.',
    'admin.users.cancel': 'Cancel',
    'admin.users.confirm': 'Confirm',
    'admin.users.toast_role': 'Updated role for {name}',
    'admin.users.toast_activated': 'Activated account {name}',
    'admin.users.toast_locked': 'Locked account {name}',
    'admin.users.toast_deleted': 'Deleted account {name}',
    'admin.users.confirm_delete': 'Are you sure you want to delete {name}\'s account?',

    // Admin - Vendors
    'admin.vendors.title': 'Approve Stores',
    'admin.vendors.subtitle': 'Manage and approve stores registered in the system.',
    'admin.vendors.search': 'Search by store name...',
    'admin.vendors.filter': 'Filter',
    'admin.vendors.pending': 'Pending',
    'admin.vendors.active': 'Active',
    'admin.vendors.rejected': 'Rejected',
    'admin.vendors.closed': 'Closed',
    'admin.vendors.no_desc': 'No description for this store.',
    'admin.vendors.no_cert': 'No certification',
    'admin.vendors.approve': 'Approve',
    'admin.vendors.view': 'View details',
    'admin.vendors.empty': 'No requests',
    'admin.vendors.empty_desc': 'There are no stores pending approval or matching your search.',
    'admin.vendors.toast_approved': 'Approved store {name}',

    // Manager - Vendor
    'manager.vendor.title': 'My Store',
    'manager.vendor.subtitle': 'Manage your store information and activity status.',
    'manager.vendor.add_title': 'Register Store',
    'manager.vendor.edit_title': 'Update Store',
    'manager.vendor.card_title': 'Store Details',
    'manager.vendor.card_desc': 'Update the basic information about your store.',
    'manager.vendor.name': 'Store name',
    'manager.vendor.name_placeholder': 'e.g. Bách Khoa Lunch...',
    'manager.vendor.cert': 'Certification / License',
    'manager.vendor.cert_placeholder': 'Business License, Food Safety...',
    'manager.vendor.desc': 'Store description',
    'manager.vendor.desc_placeholder': 'Describe your store, signature dishes...',
    'manager.vendor.open': 'Opening time',
    'manager.vendor.close': 'Closing time',
    'manager.vendor.save': 'Save Info',
    'manager.vendor.submit': 'Submit Request',
    'manager.vendor.stats': 'Quick Stats',
    'manager.vendor.completed': 'Completed orders',
    'manager.vendor.menu': 'Menu items',
    'manager.vendor.tip_title': 'Tip',
    'manager.vendor.tip_desc': 'A complete description and certification image helps customers trust and choose your food.',
    'manager.vendor.no_vendor': 'No Vendor Found',
    'manager.vendor.no_vendor_desc': 'Register your first vendor to start selling on BKafeteria.',
    'manager.vendor.dialog_desc': 'Build your brand and manage your store operations professionally.',
    'manager.vendor.dialog_hint': 'Providing complete information helps Admin approve your store faster.',
    'manager.vendor.toast_register_success': 'Vendor registration request sent!',
    'manager.vendor.toast_success': 'Store information updated successfully',
    'manager.vendor.toast_error': 'Update failed, please try again',
    'manager.vendor.status_pending': 'Pending',
    'manager.vendor.status_accepted': 'Active',
    'manager.vendor.status_rejected': 'Rejected',
    'manager.vendor.status_closed': 'Closed',

    // Manager - Menu
    'manager.menu.title': 'Manage Menu',
    'manager.menu.subtitle': 'Add, edit, delete and track menu item quantities.',
    'manager.menu.add': 'Add item',
    'manager.menu.search': 'Search menu items...',
    'manager.menu.empty': 'No items found',
    'manager.menu.empty_desc': 'Try changing the search keyword or add a new item to your menu.',
    'manager.menu.edit_title': 'Update Item',
    'manager.menu.add_title': 'Add New Item',
    'manager.menu.dialog_desc': 'Enter menu item details for customers to order.',
    'manager.menu.dialog_add_hint': 'Create new item quickly',
    'manager.menu.dialog_update_hint': 'Update item appearance',
    'manager.menu.form_image': 'Item image',
    'manager.menu.field_name': 'Item name',
    'manager.menu.field_name_placeholder': 'e.g. Grilled pork rice...',
    'manager.menu.field_price': 'Price (VND)',
    'manager.menu.field_remaining': 'Remaining quantity',
    'manager.menu.field_category': 'Category',
    'manager.menu.field_category_select': 'Select category',
    'manager.menu.field_desc': 'Description',
    'manager.menu.field_desc_placeholder': 'Ingredients, flavours...',
    'manager.menu.cancel': 'Cancel',
    'manager.menu.save': 'Save changes',
    'manager.menu.submit': 'Add item',
    'manager.menu.toast_updated': 'Item updated successfully',
    'manager.menu.toast_added': 'New item added successfully',
    'manager.menu.confirm_delete': 'Are you sure you want to delete this item?',
    'manager.menu.no_desc': 'No description for this item.',
    'manager.menu.no_image': 'No Image',
    'manager.menu.price': 'Price',
    'manager.menu.remaining': 'Remaining',

    // Manager - Orders
    'manager.orders.title': 'Manage Orders',
    'manager.orders.subtitle': 'Track and process incoming orders.',
    'manager.orders.processing': 'Processing',
    'manager.orders.history': 'Order History',
    'manager.orders.vendor_order_id': 'Vendor Order ID:',
    'manager.orders.finish': 'Complete',
    'manager.orders.empty_active': 'No pending orders.',
    'manager.orders.empty_history': 'No order history yet.',
    'manager.orders.toast_finished': 'Order marked as completed!',
    'manager.orders.process': 'Process',
    'manager.orders.sort': 'Sort',
    'manager.orders.newest': 'Newest',
    'manager.orders.oldest': 'Oldest',
    'manager.orders.toast_processing': 'Order is being processed',

    // Manager - Staff
    'manager.staff.title': 'Manage Staff',
    'manager.staff.subtitle': 'Manage your vendor\'s service team.',
    'manager.staff.add': 'Add staff',
    'manager.staff.search': 'Search staff by name...',
    'manager.staff.remove': 'Remove staff',
    'manager.staff.empty': 'No staff yet',
    'manager.staff.empty_desc': 'Staff help you process orders faster. Add a new staff member now!',
    'manager.staff.note_title': 'Note',
    'manager.staff.note_1': 'Only users with a BKafeteria account can be added as staff.',
    'manager.staff.note_2': 'Staff can view and process orders belonging to your vendor.',
    'manager.staff.support_title': 'Support',
    'manager.staff.support_desc': 'If you have difficulty managing staff, please contact the system Administrator.',
    'manager.staff.dialog_title': 'Add New Staff',
    'manager.staff.dialog_desc': 'Enter the user\'s email to assign them as staff for your store.',
    'manager.staff.email_label': 'User email',
    'manager.staff.email_placeholder': 'example@student.hcmut.edu.vn',
    'manager.staff.cancel': 'Cancel',
    'manager.staff.submit': 'Add now',
    'manager.staff.toast_added': 'Added {email} to staff list',
    'manager.staff.toast_error': 'User not found or an error occurred',
    'manager.staff.confirm_remove': 'Are you sure you want to remove {name} from the staff list?',
    'manager.staff.wip': 'Remove staff feature is being updated',

    // Vendor card
    'vendor_card.status_pending': 'Pending',
    'vendor_card.status_accepted': 'Open',
    'vendor_card.status_rejected': 'Closed',
    'vendor_card.status_closed': 'On break',
    'vendor_card.no_desc': 'No description for this store.',
    'vendor_card.view_menu': 'View menu',

    // Menu page extra
    'menu.default_vendor': 'Store',

    // Cart
    'cart.title': 'Cart',
    'cart.clear': 'Clear all',
    'cart.empty_title': 'Your cart is empty',
    'cart.empty_desc': "You haven't added any items yet.",
    'cart.start_shopping': 'Start shopping',
    'cart.items_unit': 'items',
    'cart.total': 'Total',
    'cart.checkout': 'Checkout Now',

    // Profile page
    'profile.title': 'User Profile',
    'profile.subtitle': 'Manage your account information and settings.',
    'profile.balance': 'Balance',
    'profile.points': 'Points',
    'profile.status': 'Status',
    'profile.verified': 'Verified',
    'profile.personal_info': 'Personal Information',
    'profile.personal_info_desc': 'Update your basic information for identification.',
    'profile.account_info': 'Account Information',
    'profile.account_info_desc': 'Identity information that cannot be changed.',
    'profile.fullname': 'Full Name',
    'profile.phone': 'Phone Number',
    'profile.gender': 'Gender',
    'profile.dob': 'Date of Birth',
    'profile.email': 'Email',
    'profile.student_id': 'Student ID',
    'profile.save': 'Save Changes',
    'profile.toast_success': 'Profile updated successfully',
    'profile.toast_error': 'Update failed',

    'cart.subtotal': 'Subtotal',
    'cart.service_fee': 'Service fee',
    'cart.free': 'Free',
    'cart.processing': 'Processing...',
    'cart.toast_success': 'Order placed successfully!',
    'cart.toast_error': 'An error occurred while placing the order',
    'cart.providers.title': 'Your cart',
    'cart.providers.empty': 'No items yet',
    'cart.providers.total': 'Total:',
    'cart.providers.total_price': 'Total:',
    'cart.providers.checkout': 'Checkout',
    'cart.providers.added': 'Added {name} to cart',

    // Roles
    'role.admin': 'Admin',
    'role.manager': 'Manager',
    'role.staff': 'Staff',
    'role.customer': 'Customer',

    // Common
    'common.cancel': 'Cancel',
    'common.search': 'Search...',
    'common.filter': 'Filter',
    'common.switch_lang': 'Switch Language',
    'common.vi': 'Vietnamese',
    'common.en': 'English',
    'common.change_to_vi': 'Switch to Vietnamese',
    'common.change_to_en': 'Switch to English',

    // Categories
    'category.beverages': 'Beverages',
    'category.pastries': 'Pastries',
    'category.snacks': 'Snacks',
    'category.meals': 'Meals',
    'category.desserts': 'Desserts',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.confirm': 'Confirm',
    'status.active': 'Active',
    'status.inactive': 'Inactive',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState<Lang>('vi')

  useEffect(() => {
    const saved = localStorage.getItem('lang') as Lang | null
    if (saved === 'vi' || saved === 'en') setLangState(saved)
  }, [])

  const setLang = (l: Lang) => {
    setLangState(l)
    localStorage.setItem('lang', l)
  }

  const t = (key: string) => translations[lang][key] ?? key

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}
