server:
  port: ${API_GATEWAY}

spring:
# JWT Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            # API Routes
            - id: iam-service
              uri: http://localhost:${IAM_SERVICE}
              predicates:
                - Path=/api/iam/**
              filters:
                - StripPrefix=1
                
            - id: vendor-service
              uri: http://localhost:${VENDOR_SERVICE}
              predicates:
                - Path=/api/vendor/**
              filters:
                - StripPrefix=1

            - id: menu-service
              uri: http://localhost:${MENU_SERVICE}
              predicates:
                - Path=/api/menu/**
              filters:
                - StripPrefix=1

            - id: order-service
              uri: http://localhost:${ORDER_SERVICE}
              predicates:
                - Path=/api/order/**
              filters:
                - StripPrefix=1 

            # API Documentation Routes  
            - id: iam-service-api-docs
              uri: http://localhost:${IAM_SERVICE}
              predicates:
                - Path=/iam/v3/api-docs
              filters:
                - StripPrefix=1 
                
            - id: vendor-service-api-docs
              uri: http://localhost:${vendor_SERVICE}
              predicates:
                - Path=/vendor/v3/api-docs
              filters:
                - StripPrefix=1 

            - id: menu-service-api-docs
              uri: http://localhost:${MENU_SERVICE}
              predicates:
                - Path=/menu/v3/api-docs
              filters:
                - StripPrefix=1

            - id: order-service-api-docs
              uri: http://localhost:${ORDER_SERVICE}
              predicates:
                - Path=/order/v3/api-docs
              filters:
                - StripPrefix=1 

  application:
    name: api-gateway

# SpringDoc configuration
springdoc:
  swagger-ui:
    urls:
      - name: IAM Service
        url: http://localhost:${IAM_SERVICE}/iam/v3/api-docs
      - name: vendor Service
        url: http://localhost:${VENDOR_SERVICE}/vendor/v3/api-docs
      - name: Order Service
        url: http://localhost:${ORDER_SERVICE}/order/v3/api-docs
      - name: Menu Service
        url: http://localhost:${MENU_SERVICE}/menu/v3/api-docs
    path: /swagger-ui.html
    display-request-duration: true
    operations-sorter: method
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: true

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
    root: INFO
